global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'polymarket'
    static_configs:
      - targets: [ '127.0.0.1:9101', '127.0.0.1:9102', '127.0.0.1:9103', '127.0.0.1:9104' ]
        labels:
          currency: 'btc'
      - targets: [ '127.0.0.1:9105', '127.0.0.1:9106', '127.0.0.1:9107', '127.0.0.1:9108' ]
        labels:
          currency: 'eth'
      - targets: [ '127.0.0.1:9109', '127.0.0.1:9110', '127.0.0.1:9111', '127.0.0.1:9112' ]
        labels:
          currency: 'sol'
      - targets: [ '127.0.0.1:9113', '127.0.0.1:9114', '127.0.0.1:9115', '127.0.0.1:9116' ]
        labels:
          currency: 'xrp'

